/**
 * This _should_ be automatically generated however
 * there is no need to do so right now.
 */
#ifndef DRM_MODIFIERS_H
#define DRM_MODIFIERS_H

#define DrmModifiersList \
  { "DRM_FORMAT_MOD_INVALID", DRM_FORMAT_MOD_INVALID }, \
  { "DRM_FORMAT_MOD_LINEAR", DRM_FORMAT_MOD_LINEAR }, \
  { "I915_FORMAT_MOD_X_TILED", I915_FORMAT_MOD_X_TILED }, \
  { "I915_FORMAT_MOD_Y_TILED", I915_FORMAT_MOD_Y_TILED }, \
  { "I915_FORMAT_MOD_Yf_TILED", I915_FORMAT_MOD_Yf_TILED }, \
  { "I915_FORMAT_MOD_Y_TILED_CCS", I915_FORMAT_MOD_Y_TILED_CCS }, \
  { "I915_FORMAT_MOD_Yf_TILED_CCS", I915_FORMAT_MOD_Yf_TILED_CCS }, \
  { "I915_FORMAT_MOD_Y_TILED_GEN12_RC_CCS", I915_FORMAT_MOD_Y_TILED_GEN12_RC_CCS }, \
  { "I915_FORMAT_MOD_Y_TILED_GEN12_MC_CCS", I915_FORMAT_MOD_Y_TILED_GEN12_MC_CCS }, \
  { "I915_FORMAT_MOD_Y_TILED_GEN12_RC_CCS_CC", I915_FORMAT_MOD_Y_TILED_GEN12_RC_CCS_CC }, \
  { "I915_FORMAT_MOD_4_TILED", I915_FORMAT_MOD_4_TILED }, \
  { "I915_FORMAT_MOD_4_TILED_DG2_RC_CCS", I915_FORMAT_MOD_4_TILED_DG2_RC_CCS }, \
  { "I915_FORMAT_MOD_4_TILED_DG2_MC_CCS", I915_FORMAT_MOD_4_TILED_DG2_MC_CCS }, \
  { "I915_FORMAT_MOD_4_TILED_DG2_RC_CCS_CC", I915_FORMAT_MOD_4_TILED_DG2_RC_CCS_CC }, \
  { "I915_FORMAT_MOD_4_TILED_MTL_RC_CCS", I915_FORMAT_MOD_4_TILED_MTL_RC_CCS }, \
  { "I915_FORMAT_MOD_4_TILED_MTL_MC_CCS", I915_FORMAT_MOD_4_TILED_MTL_MC_CCS }, \
  { "I915_FORMAT_MOD_4_TILED_MTL_RC_CCS_CC", I915_FORMAT_MOD_4_TILED_MTL_RC_CCS_CC }, \
  { "I915_FORMAT_MOD_4_TILED_LNL_CCS", I915_FORMAT_MOD_4_TILED_LNL_CCS }, \
  { "I915_FORMAT_MOD_4_TILED_BMG_CCS", I915_FORMAT_MOD_4_TILED_BMG_CCS }, \
  { "DRM_FORMAT_MOD_SAMSUNG_64_32_TILE", DRM_FORMAT_MOD_SAMSUNG_64_32_TILE }, \
  { "DRM_FORMAT_MOD_SAMSUNG_16_16_TILE", DRM_FORMAT_MOD_SAMSUNG_16_16_TILE }, \
  { "DRM_FORMAT_MOD_QCOM_COMPRESSED", DRM_FORMAT_MOD_QCOM_COMPRESSED }, \
  { "DRM_FORMAT_MOD_QCOM_TILED3", DRM_FORMAT_MOD_QCOM_TILED3 }, \
  { "DRM_FORMAT_MOD_QCOM_TILED2", DRM_FORMAT_MOD_QCOM_TILED2 }, \
  { "DRM_FORMAT_MOD_VIVANTE_TILED", DRM_FORMAT_MOD_VIVANTE_TILED }, \
  { "DRM_FORMAT_MOD_VIVANTE_SUPER_TILED", DRM_FORMAT_MOD_VIVANTE_SUPER_TILED }, \
  { "DRM_FORMAT_MOD_VIVANTE_SPLIT_TILED", DRM_FORMAT_MOD_VIVANTE_SPLIT_TILED }, \
  { "DRM_FORMAT_MOD_VIVANTE_SPLIT_SUPER_TILED", DRM_FORMAT_MOD_VIVANTE_SPLIT_SUPER_TILED }, \
  { "DRM_FORMAT_MOD_NVIDIA_TEGRA_TILED", DRM_FORMAT_MOD_NVIDIA_TEGRA_TILED }, \
  { "DRM_FORMAT_MOD_BROADCOM_VC4_T_TILED", DRM_FORMAT_MOD_BROADCOM_VC4_T_TILED }, \
  { "DRM_FORMAT_MOD_BROADCOM_UIF", DRM_FORMAT_MOD_BROADCOM_UIF }, \
  { "DRM_FORMAT_MOD_ALLWINNER_TILED", DRM_FORMAT_MOD_ALLWINNER_TILED }, \
  { "DRM_FORMAT_MOD_APPLE_GPU_TILED", DRM_FORMAT_MOD_APPLE_GPU_TILED }, \
  { "DRM_FORMAT_MOD_APPLE_GPU_TILED_COMPRESSED", DRM_FORMAT_MOD_APPLE_GPU_TILED_COMPRESSED }, \
  { "AMD_FMT_MOD_TILE_VERSION_MASK", AMD_FMT_MOD_TILE_VERSION_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_TILE_MASK", AMD_FMT_MOD_TILE_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_MASK", AMD_FMT_MOD_DCC_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_RETILE_MASK", AMD_FMT_MOD_DCC_RETILE_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_PIPE_ALIGN_MASK", AMD_FMT_MOD_DCC_PIPE_ALIGN_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_INDEPENDENT_64B_MASK", AMD_FMT_MOD_DCC_INDEPENDENT_64B_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_INDEPENDENT_128B_MASK", AMD_FMT_MOD_DCC_INDEPENDENT_128B_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_MAX_COMPRESSED_BLOCK_MASK", AMD_FMT_MOD_DCC_MAX_COMPRESSED_BLOCK_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_DCC_CONSTANT_ENCODE_MASK", AMD_FMT_MOD_DCC_CONSTANT_ENCODE_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_PIPE_XOR_BITS_MASK", AMD_FMT_MOD_PIPE_XOR_BITS_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_BANK_XOR_BITS_MASK", AMD_FMT_MOD_BANK_XOR_BITS_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_PACKERS_MASK", AMD_FMT_MOD_PACKERS_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_RB_MASK", AMD_FMT_MOD_RB_MASK | AMD_FMT_MOD }, \
  { "AMD_FMT_MOD_PIPE_MASK", AMD_FMT_MOD_PIPE_MASK | AMD_FMT_MOD }, \
  { NULL, 0 },

#endif // DRM_MODIFIERS_H
